### ISSUE TITLE
Mezera mezi topics

### ISSUE THREAD

**Issue by timkol** [fykosak/dokuwiki-plugin-fkstaskrepo#10]
Byl by dobrý nějaký oddělovač (mezera) mezi více topicy u zadání úlohy, viz R31S1U8 na stránkách.

**Comment by cevro** [comment]
vyriešené v https://github.com/fykosak/dokuwiki-plugin-fkstaskrepo/commit/768e3b1dbabdda5a94916246483e1d09982252a8 

Zatiaľ nenasadené - čaká sa na odsúhlasenie zmien grafiky.
